version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/_provisioning"
    schedule:
      interval: "monthly"
      time: "00:00"
      timezone: "Asia/Seoul"
    reviewers:
      - "HardBoiledSmith/code-reviewer"
