version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r _provisioning/requirements.txt
      - pip install flake8

  build:
    commands:
      - flake8 --config=flake8 .
