version: 0.2

phases:
  install:
    commands:
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2701 https://github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
    finally:
      - cd magi/_seele
      - ls
      - pwd
  pre_build:
    commands:
      - command
    finally:
      - command
  build:
    commands:
      - command
    finally:
      - command
  post_build:
    commands:
      - command
