version: 0.2

phases:
  install:
    commands:
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2717 https://$GITHUB_TOKEN@github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
      - cp magi/_seele/dv-chhyun-config.json ../config.json
      - cp magi/_seele/dv-chhyun-20180809.* ../
      - pip install awscli --upgrade --user
      - export PATH=~/.local/bin:$PATH
      - npm install -g npm@latest
      - npm install -g which-pm-runs-cli
      - npm install -g grunt-cli
      - npm install -g standard
      - yum install -y zip
      - yum install -y python36
      - yum install -y python36-devel
      - yum install -y python36-setuptools
      - easy_install-3.6 pip
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
      - export PATH=~/.yarn/bin:$PATH
      - yum install -y bzip2
  build:
    commands:
      - cd ..
      - ./run.py -f create
  post_build:
    commands:
      - ./run.py -f describe


version: 0.2

phases:
  install:
    commands:
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2717 https://$GITHUB_TOKEN@github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
      - cp magi/_seele/dv-chhyun-config.json ../config.json
      - cp magi/_seele/dv-chhyun-20180809.* ../
      - pip install awscli --upgrade --user
      - export PATH=~/.local/bin:$PATH
      - npm install -g npm@latest
      - npm install -g which-pm-runs-cli
      - npm install -g grunt-cli
      - npm install -g standard
      - yum install -y zip
      - yum install -y python36
      - yum install -y python36-devel
      - yum install -y python36-setuptools
      - easy_install-3.6 pip
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
      - export PATH=~/.yarn/bin:$PATH
      - yum install -y bzip2
  build:
    commands:
      - cd ..
      - ./run_create_s3.py -f
      - ./run_create_cloudwatch_alarm.py -f
      - ./run_create_cloudwatch_dashboard.py -f



version: 0.2

phases:
  install:
    commands:
      - yum install -y bzip2
      - yum install -y fontconfig freetype freetype-devel fontconfig-devel libstdc++
      - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
      - mkdir -p /opt/phantomjs
      - bzip2 -d phantomjs-1.9.8-linux-x86_64.tar.bz2
      - tar -xvf phantomjs-1.9.8-linux-x86_64.tar --directory /opt/phantomjs/ --strip-components 1
      - ln -s /opt/phantomjs/bin/phantomjs /usr/bin/phantomjs
      - phantomjs --version
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2717 https://$GITHUB_TOKEN@github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
      - cp magi/_seele/dv-chhyun-config.json ../config.json
      - cp magi/_seele/dv-chhyun-20180809.* ../
      - pip install awscli --upgrade --user
      - export PATH=~/.local/bin:$PATH
      - npm install -g npm@latest
      - npm install -g which-pm-runs-cli
      - npm install -g grunt-cli
      - npm install -g standard
      - yum install -y zip
      - yum install -y python36
      - yum install -y python36-devel
      - yum install -y python36-setuptools
      - easy_install-3.6 pip
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
      - export PATH=~/.yarn/bin:$PATH
  build:
    commands:
      - cd ..
      - ./run_create_s3.py -f
    finally:
      - cd ./template/magi/s3/hbsmith-web-root/hbsmith-web-root/root
      - grunt
