version: 0.2

phases:
  install:
    commands:
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2717 https://$GITHUB_TOKEN@github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
      - cp magi/_seele/dv-chhyun-config.json ../config.json
      - cp magi/_seele/dv-chhyun-20180809.* ../
      - pip install awscli --upgrade --user
      - export PATH=~/.local/bin:$PATH
      - npm install -g npm@latest
      - npm install -g which-pm-runs-cli
      - npm install -g grunt-cli
      - npm install -g standard
      - yum install -y python36
      - yum install -y zip
  build:
    commands:
      - cd ..
      - ./run.py -f create
  post_build:
    commands:
      - ./run.py -f describe
