version: 0.2

phases:
  install:
    commands:
      - yum install -y git-core
      - mkdir template
      - cd template
      - git clone -b GEN-2701 https://$GITHUB_TOKEN@github.com/HardBoiledSmith/magi.git
      - unzip -P $SEELE_ZIP_PASSWORD ./magi/_seele/$SEELE_ZIP -d ./magi/_seele
      - cp magi/_seele/dv-chhyun-config.json ../config.json
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
      - nvm install node
      - npm install -g npm@latest
      - npm install -g which-pm-runs-cli
      - npm install -g grunt-cli
      - npm install -g standard
  pre_build:
    commands:
      - cd ..
      - pwd
      - ls
  build:
    commands:
      - command
    finally:
      - command
  post_build:
    commands:
      - command
