# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hbsmith/awslinux2"

  config.vm.provider "parallels" do |prl|
    prl.name = 'hbsmith-johanna'
    prl.cpus = 2
    prl.memory = 2048
  end

  config.vm.provision "file", source: "../config.json", destination: "/vagrant/opt/johanna/config.json"
  config.vm.provision "shell", inline: "yum -y install python37"
  config.vm.provision "shell", path: "provisioning.py", reboot: true
  config.vm.network "private_network", ip: "192.168.124.5"
end
