# -*- mode: ruby -*-
# vi: set ft=ruby :

def is_arm64()
  `uname -m` == "arm64" || `/usr/bin/arch -64 sh -c "sysctl -in sysctl.proc_translated"`.strip() == "0"
end

Vagrant.configure(2) do |config|
  if is_arm64()
    config.vm.box = "hbsmith/fedora-35-aarch64"
  else
    config.vm.box = "hbsmith/awslinux2"
  end

  config.vm.provider "parallels" do |prl|
    prl.name = 'hbsmith-johanna'
    prl.cpus = 2
    prl.memory = 2048
  end

  config.vm.provision "file", source: "../config.json", destination: "/vagrant/opt/johanna/config.json"

  if config.vm.box == "hbsmith/awslinux2"
    config.vm.provision "shell", inline: "amazon-linux-extras enable python3.8"
    config.vm.provision "shell", inline: "yum -y install python38 python38-devel"
    config.vm.provision "shell", inline: "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1"
  else
    config.vm.provision "shell", inline: "dnf -y install python3.8"
    config.vm.provision "shell", inline: "python3.8 -m ensurepip --user"
  end

  config.vm.provision "shell", path: "provisioning.py", env: { "BRANCH" => ENV["BRANCH"] }, reboot: true
  config.vm.network "private_network", ip: "192.168.124.5"
end
