# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hbsmith/fedora-35-aarch64"

  config.vm.provider "parallels" do |prl|
    prl.name = 'hbsmith-johanna'
    prl.cpus = 2
    prl.memory = 2048
  end

  config.vm.provision "file", source: "../config.json", destination: "/vagrant/opt/johanna/config.json"
  config.vm.provision "shell", inline: <<-SHELL
sed -i -r -e "
/^metalink=/s/^/#/
/^#*baseurl=/{s/^#//
s%download.(fedoraproject.org|example)\%archives.fedoraproject.org%
s%(/pub)(/fedora/)%\\1/archive\\2%}
" /etc/yum.repos.d/fedora*.repo
    SHELL
    config.vm.provision "shell", inline: "dnf -y install python3.8"
    config.vm.provision "shell", inline: "python3.8 -m ensurepip --user"
  end

  config.vm.provision "shell", path: "provisioning.py", env: { "BRANCH" => ENV["BRANCH"] }, reboot: true
  config.vm.network "private_network", ip: "192.168.124.5"
end
